name: CI Automation Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          playwright install --with-deps

      - name: Run Pytest
        run: pytest --maxfail=1 --disable-warnings -q --html=reports/test-report.html --self-contained-html

      - name: Upload report
        uses: actions/upload-artifact@v4
        with:
          name: test-report
          path: reports/test-report.html
